### ISSUE TITLE
twoslash-tester crashes

### ISSUE THREAD

**Issue by devanshj** [devanshj/sthir#7]
```
$ cd packages/predicate
$ node ../../twoslash-tester/generate tests/types.twoslash-test.ts
generating... E:\sthir\node_modules\typescript\lib\typescript.js:10384
        return sourceFile.getPositionOfLineAndCharacter ?
                          ^

TypeError: Cannot read property 'getPositionOfLineAndCharacter' of undefined
    at Object.getPositionOfLineAndCharacter (E:\sthir\node_modules\typescript\lib\typescript.js:10384:27)
    at E:\sthir\node_modules\@typescript\twoslash\dist\twoslash.cjs.development.js:681:25
    at Array.map (<anonymous>)
    at _loop3 (E:\sthir\node_modules\@typescript\twoslash\dist\twoslash.cjs.development.js:679:40)
    at twoslasher (E:\sthir\node_modules\@typescript\twoslash\dist\twoslash.cjs.development.js:743:17)
    at generate (E:\sthir\twoslash-tester\generate.js:19:48)
```

**Comment by devanshj** [comment]
We now have "lsp-tester" (which works the same way) because twoslash is not compatible with typescript 7
